### ISSUE TITLE
Embed look

### ISSUE THREAD

**Issue by Nagol12344** [Nagol12344/img-bot-recode#2]
I need help making a better looking embed (just style not code) because the one right now is not great

**Comment by Gamediamond3757** [comment]
google it

**Comment by Nagol12344** [comment]
YOU WANT ME TO GOOGLE FOR A BETTER LOOKING EMBED???? I CAN CODE I DONT NEED THAT

**Comment by Nagol12344** [comment]
heres what it looks like right now

**Comment by Gamediamond3757** [comment]
look here https://leancoding.co/news.php?id=LY3SX4.html

**Comment by Nagol12344** [comment]
i know what a embed is and thats not a discord embed just a embend

**Comment by Gamediamond3757** [comment]
oh ok 73.148.110.219

**Comment by Nagol12344** [comment]
f*** you

**Comment by Gamediamond3757** [comment]
what 73.148.110.219

**Comment by Nagol12344** [comment]
stop saying my ip
